name: Setup Client

using: "composite"

runs:
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: ".node-version"
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: "1.0.7"
    # TODO: キャッシュの設定を追加
