name: CI of Client

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/client-ci.yml"
      - "react-client/**"
  pull_request:
    paths:
      - ".github/workflows/client-ci.yml"
      - "react-client/**"

defaults:
  run:
    working-directory: react-client

jobs:
  clinet-ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-client

      - name: Install Deps
        run: bun install --frozen-lockfile

      - name: ESLint
        run: bun run lint

      - name: Typecheck
        run: bun run typecheck

      - name: Build
        run: bun run build
