name: CI of Client

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/client-ci.yml"
      - "client/**"

defaults:
  run:
    working-directory: client

jobs:
  clinet-ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-client

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: ESLint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build
